import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

/**
 * Two of these rules are load-bearing rather than stylistic.
 *
 * The `unsafeDb` ban is what makes the tenancy guarantee hold. The scoping
 * extension is bypassed by anyone who imports the raw client, and that mistake
 * is invisible in review because the query looks correct — it just returns
 * every tenant's rows.
 *
 * The raw-SQL ban closes the other hole. `$queryRaw` goes straight to Postgres
 * with no extension in the path, so a raw query in a service is an unscoped
 * query by construction.
 */
const TENANCY_RULES = {
  'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: '@/server/db',
          importNames: ['unsafeDb'],
          message:
            'unsafeDb is not tenant-scoped. Use ctx.db, which is. If you genuinely need the raw client, it is available in src/server/ctx.ts, the seed and the tests.',
        },
        {
          name: '@/server/db.ts',
          importNames: ['unsafeDb'],
          message:
            'unsafeDb is not tenant-scoped. Use ctx.db, which is. If you genuinely need the raw client, it is available in src/server/ctx.ts, the seed and the tests.',
        },
      ],
    },
  ],
  'no-restricted-syntax': [
    'error',
    {
      selector:
        'MemberExpression[property.name=/^\\$(queryRaw|queryRawUnsafe|executeRaw|executeRawUnsafe)$/]',
      message:
        'Raw SQL bypasses the tenant-scoping extension entirely. Keep it inside src/server/db.ts, a migration, or a test.',
    },
  ],
}

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by `prisma generate`, never edited, and not ours to lint.
    'src/generated/**',
  ]),

  {
    files: ['src/**/*.{ts,tsx}'],
    rules: TENANCY_RULES,
  },

  {
    // The three places allowed to hold the unscoped client, plus the health
    // check, which exists precisely to prove the raw connection works.
    files: [
      'src/server/db.ts',
      'src/server/ctx.ts',
      // The complete list of reads that discover a scope rather than operating
      // inside one. All but `emailHasAccount` are filtered by a caller-supplied
      // key; that one is an enumeration oracle by design and is rate limited at
      // its route. See docs/03-ARCHITECTURE.md.
      'src/server/scope-resolution.ts',
      'src/app/api/health/route.ts',
      'tests/**/*.ts',
    ],
    rules: {
      'no-restricted-imports': 'off',
      'no-restricted-syntax': 'off',
    },
  },
])

export default eslintConfig
