/**
 * Logistics requests.
 *
 * The other write the offline queue holds. A projector dies in a basement
 * committee room with no signal; if the request cannot be typed there it is
 * typed nowhere, and the runner never hears about it.
 */

import { z } from 'zod'
import type { Prisma } from '@/generated/prisma/client.ts'
import { scopedCreate } from '../db.ts'
import { requireConference, requireUser, type Ctx } from '../ctx.ts'
import { ApiError } from '../errors.ts'
import { runSerializable } from '../transaction.ts'

export const LOGISTICS_CATEGORIES = [
  'EQUIPMENT',
  'STATIONERY',
  'REFRESHMENT',
  'TECHNICAL',
  'MEDICAL',
  'TRANSPORT',
  'OTHER',
] as const

export const LOGISTICS_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED'] as const

export const logisticsFiltersSchema = z.object({
  status: z.enum(LOGISTICS_STATUSES).optional(),
  category: z.enum(LOGISTICS_CATEGORIES).optional(),
  committeeId: z.uuid().optional(),
})

export const createLogisticsSchema = z.object({
  title: z.string().trim().min(3, 'Say what is needed').max(140),
  detail: z.string().trim().max(2000).optional(),
  category: z.enum(LOGISTICS_CATEGORIES).default('OTHER'),
  priority: z.enum(['LOW', 'NORMAL', 'URGENT']).default('NORMAL'),
  committeeId: z.uuid().optional(),
  /**
   * Generated by the browser before the request is queued. Present only for a
   * write that went through the offline queue; a request typed online has no
   * replay to protect against.
   */
  clientRequestId: z.uuid().optional(),
})

/**
 * Resolution is required to close, and not to cancel.
 *
 * "Resolved" with no note is the state that makes a logistics board useless the
 * following year: nobody can tell whether the chairs arrived or whether someone
 * cleared the list at midnight.
 */
export const updateLogisticsSchema = z
  .object({
    status: z.enum(LOGISTICS_STATUSES),
    resolution: z.string().trim().max(2000).optional(),
  })
  .refine((value) => value.status !== 'RESOLVED' || (value.resolution ?? '').length >= 3, {
    path: ['resolution'],
    message: 'Say what was done, so this reads as an answer next year',
  })

export type LogisticsFilters = z.infer<typeof logisticsFiltersSchema>
export type CreateLogisticsInput = z.infer<typeof createLogisticsSchema>
export type UpdateLogisticsInput = z.infer<typeof updateLogisticsSchema>

const LIST_INCLUDE = {
  committee: { select: { id: true, code: true, name: true } },
  requestedBy: { select: { id: true, fullName: true, email: true } },
  resolvedBy: { select: { id: true, fullName: true, email: true } },
} as const

export async function listLogistics(ctx: Ctx, filters: LogisticsFilters = {}) {
  requireConference(ctx)

  return ctx.db.logisticsRequest.findMany({
    where: {
      ...(filters.status ? { status: filters.status } : {}),
      ...(filters.category ? { category: filters.category } : {}),
      ...(filters.committeeId ? { committeeId: filters.committeeId } : {}),
    },
    // Urgent first, then oldest first inside a priority. A board sorted purely
    // by time buries the thing that is on fire under nine requests for pens.
    orderBy: [{ status: 'asc' }, { priority: 'desc' }, { createdAt: 'asc' }],
    include: LIST_INCLUDE,
  })
}

export async function logisticsSummary(ctx: Ctx) {
  requireConference(ctx)

  const grouped = await ctx.db.logisticsRequest.groupBy({
    by: ['status'],
    _count: { _all: true },
  })

  const counts: Record<(typeof LOGISTICS_STATUSES)[number], number> = {
    OPEN: 0,
    IN_PROGRESS: 0,
    RESOLVED: 0,
    CANCELLED: 0,
  }
  for (const row of grouped) counts[row.status] = row._count._all

  const urgent = await ctx.db.logisticsRequest.count({
    where: { priority: 'URGENT', status: { in: ['OPEN', 'IN_PROGRESS'] } },
  })

  return { ...counts, urgentOutstanding: urgent }
}

/**
 * Raises a request.
 *
 * **Idempotent when the caller supplies `clientRequestId`.** A queued POST is
 * replayed on reconnect, and there is no natural key that separates "more
 * chairs in UNSC" typed twice on purpose from the same request flushed twice.
 * Without the token a flaky connection multiplies every request by the number
 * of times the flush ran.
 *
 * The replay returns the original row with the original 201, exactly as the
 * public registration endpoint does for a duplicate submission — the caller
 * cannot tell the two apart, which is the property that makes retrying safe.
 *
 * CONTRIBUTOR is enough to raise one, because the person who notices is rarely
 * the person with the admin grant.
 */
export async function createLogisticsRequest(ctx: Ctx, input: CreateLogisticsInput) {
  requireConference(ctx)
  const actor = requireUser(ctx)

  return runSerializable(ctx.db, async (tx) => {
    if (input.clientRequestId) {
      const replayed = await tx.logisticsRequest.findFirst({
        where: { clientRequestId: input.clientRequestId },
        include: LIST_INCLUDE,
      })
      if (replayed) {
        /*
          The replay is audited too.

          Two reasons. It keeps "every mutating admin route writes an AuditLog
          row" literally true rather than true-except-here, which is the kind of
          exception that quietly becomes three. And it is the only trace that
          the connection was bad enough for the queue to flush twice, which is
          the question asked when someone insists they submitted a request the
          board never showed.
        */
        await ctx.audit.record(
          {
            action: 'logistics.replay',
            entityType: 'LogisticsRequest',
            entityId: replayed.id,
            payloadAfter: { clientRequestId: input.clientRequestId },
          },
          tx,
        )
        return { request: replayed, replayed: true }
      }
    }

    if (input.committeeId) {
      const committee = await tx.committee.findFirst({
        where: { id: input.committeeId },
        select: { id: true },
      })
      if (!committee) throw ApiError.notFound('That committee is not in this conference')
    }

    const request = await tx.logisticsRequest.create({
      data: scopedCreate<Prisma.LogisticsRequestUncheckedCreateInput>({
        title: input.title,
        detail: input.detail ?? null,
        category: input.category,
        priority: input.priority,
        committeeId: input.committeeId ?? null,
        clientRequestId: input.clientRequestId ?? null,
        requestedByUserId: actor.id,
      }),
      include: LIST_INCLUDE,
    })

    await ctx.audit.record(
      {
        action: 'logistics.create',
        entityType: 'LogisticsRequest',
        entityId: request.id,
        payloadAfter: {
          title: request.title,
          category: request.category,
          priority: request.priority,
          committeeId: request.committeeId,
          queued: input.clientRequestId !== undefined,
        },
      },
      tx,
    )

    return { request, replayed: false }
  })
}

export async function updateLogisticsRequest(
  ctx: Ctx,
  requestId: string,
  input: UpdateLogisticsInput,
) {
  requireConference(ctx)
  const actor = requireUser(ctx)

  const existing = await ctx.db.logisticsRequest.findFirst({ where: { id: requestId } })
  if (!existing) throw ApiError.notFound('Not found')

  const closing = input.status === 'RESOLVED' || input.status === 'CANCELLED'

  const updated = await ctx.db.logisticsRequest.update({
    where: { id: existing.id },
    data: {
      status: input.status,
      resolution: input.resolution ?? existing.resolution,
      // Reopening clears the closure rather than leaving a resolved-at in the
      // past on a request that is open again.
      resolvedAt: closing ? (existing.resolvedAt ?? new Date()) : null,
      resolvedByUserId: closing ? (existing.resolvedByUserId ?? actor.id) : null,
    },
    include: LIST_INCLUDE,
  })

  await ctx.audit.record({
    action: 'logistics.update',
    entityType: 'LogisticsRequest',
    entityId: updated.id,
    payloadBefore: { status: existing.status, resolution: existing.resolution },
    payloadAfter: { status: updated.status, resolution: updated.resolution },
  })

  return updated
}
